### ISSUE TITLE
Repeated items displayed in the first menu

### ISSUE THREAD

**Issue by kotatsuyaki** [Kumaizep/Fuz-downloader#5]
See the attached screenshot.

![Screenshot_20220903_115744](https://user-images.githubusercontent.com/17219127/188254955-a0a48520-cf28-4e54-b869-a7420ea236ee.png)

**Comment by Kumaizep** [comment]
I think it has been fixed in [522c155](https://github.com/Kumaizep/Fuz-downloader/commit/522c155a062f96dbe0b018d8ed31ea1e620a5209).
